### PR TITLE
fix: allow toast relopt inheritance from template

### LINKED ISSUE #812: Inherit template toast table's properties while creating partition.
As listed in https://www.postgresql.org/docs/current/sql-createtable.html#SQL-CREATETABLE-STORAGE-PARAMETERS, In postgres we can set toast related storage parameter while creating or altering table. But when doing the same for template table the toast specific properties are not inherited when new paritition is being created.

This is happening because we are only copying reloptions from template table pg_class entry, whereas toast specific storage parameter are stored in reloptions for the pg_toast table of the respective template table.

### PR DESCRIPTION
**Pull request by keithf4**
Fixes #812 & #848

### CODE REVIEW

File: sql/functions/inherit_template_properties.sql [hunk 1]
```diff
@@ -212,6 +213,26 @@ LOOP
...
+-- Get toast table options
+SELECT reltoastrelid INTO v_toast_table_oid
+FROM pg_catalog.pg_class c
+JOIN pg_catalog.pg_namespace n ON c.relnamespace = n.oid
+WHERE c.oid = v_template_oid;
+
+FOR v_relopt IN
+    SELECT unnest(reloptions) as value
+    FROM pg_catalog.pg_class
+    WHERE oid = v_template_oid
```
Comment (chopraanmol1) [inline sql/functions/inherit_template_properties.sql]: Replace `v_template_oid` with `v_toast_table_oid`

Comment (keithf4) [reply sql/functions/inherit_template_properties.sql]: Thanks! Glad I asked in addition to working on the unit test for it today.

Comment (keithf4) [reply sql/functions/inherit_template_properties.sql]: This has been fixed

File: test/test-id-gap-fill.sql [hunk 2]
```diff
@@ -24,6 +25,10 @@ CREATE TABLE partman_test.template_id_taptest_table (LIKE partman_test.id_taptes
 ALTER TABLE partman_test.id_taptest_table ADD PRIMARY KEY (col1);
 CREATE INDEX ON partman_test.id_taptest_table (col3);
 
+-- TODO Add checks that these settings are in place on child tables
+ALTER TABLE partman_test.template_id_taptest_table SET (autovacuum_vacuum_threshold = 100);
```
Comment (chopraanmol1) [inline test/test-id-gap-fill.sql]: Consider using a different relopt for the parent table from toast table. Right now a potential bug where partman is applying both parent tables & it's toast tables rel option to child's toast table will not fail this test. 

for parent table reloption using something like `fillfactor` might even be better because `toast.fillfactor` is not a valid reloption so in case the above mentioned potential bug gets introduced we will see failure from inherit_template_properties

File: test/test-id-gap-fill.sql [hunk 3]
```diff
@@ -54,6 +59,61 @@ SELECT is_empty('SELECT * FROM ONLY partman_test.id_taptest_table', 'Check that
 SELECT results_eq('SELECT count(*)::int FROM partman_test.id_taptest_table', ARRAY[9], 'Check count from parent table');
 SELECT results_eq('SELECT count(*)::int FROM partman_test.id_taptest_table_p3000000000', ARRAY[9], 'Check count from id_taptest_table_p3000000000');
 
+-- Check reloptions set for child table
+SELECT results_eq('WITH relopt AS (
+    SELECT unnest(reloptions) AS relopt FROM pg_class c
```
Comment (chopraanmol1) [inline test/test-id-gap-fill.sql:63]: Do we need `unnest` here? 

Currently we are testing only if the correct relopts is applied, we should ideally also test if no additional relopts is applied. Removing unnest would mean we can compare all of the relopts instead of just one.

**Review by chopraanmol1 — COMMENTED** [review]
Functionality point of view the new changes are working correctly for my use case.

File: test/test-id-gap-fill.sql (hunk 2 above)
Comment (keithf4) [reply test/test-id-gap-fill.sql]: Good suggestion, thank you.

File: test/test-id-gap-fill.sql (hunk 3 above)
Comment (keithf4) [reply test/test-id-gap-fill.sql:63]: I'm not sure if this is really necessary. If someone sets other relopts other than the ones set via the template table, that's kind of on them and I don't see any reason to disallow it nor be that concerned.

If you'd like to adjust the test to be more flexible to test for additional options like that, I wouldn't mind and would be happy to accept the PR.

Comment (keithf4) [reply test/test-id-gap-fill.sql:63]: Also just want to say thank you for your time and detailed PR reviews!

Comment (chopraanmol1) [reply test/test-id-gap-fill.sql:63]: I was not referring to user setting up additional relopts. My comment was more to ensure that we have test which make sures partman does not inherit relopts from other pg class entries. Right now with fillfactor relopts we have ensured parent table's relopts are not copied to child toast table's relopts, but nothing is verifying if parent toast relopts(or some other table's relopts) is not being copied to child table relopts.

If you feel it's not really needed right now then feel free to resolve this thread, rest of the MR already looks good. Also thanks for picking up the changes needed to resolve this issue.

Comment (keithf4) [reply test/test-id-gap-fill.sql:63]: I see. But since we're copying the relopts from a specific OID entry in pg_class, I'm curious how relopts from another pg_class entry could be obtained inadvertently? Genuinely curious if this is something you've seen before and should be a concern when doing catalog lookups like this.

Comment (chopraanmol1) [reply test/test-id-gap-fill.sql:63]: Currently I don't think that will happen as the query looks correct. The suggestion was more towards ensuring that any future changes in partman does not introduce regression where slightly incorrect pg_class query or ALTER query starts copying additional relopts. In an ideal case the tests should be able to catch regression like this, but as I mentioned if you feel it's not needed immediately then we can resolve the thread.

**Review by chopraanmol1 — APPROVED** [review]
